version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/clash_tmpl.yaml"
quanx_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/qx.ini"
surge_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/surge.conf"
managed_config_prefix = "http://home.man-her.tech:55500"
append_proxy_type=true
interval=86400
exclude_remarks=["(Traffic Reset|Expire Date|Premium|套餐到期|重置|官网|官网)"]

[[rename_node]]
import = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/base/rulesets.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/base/rulesets.toml"

[[custom_groups]]
import = "https://github.com/HYBB-rash/MyProxyRepo/blob/main/base/groups.toml"