version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/clash_tmpl.yaml"
quanx_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/qx.ini"
surge_rule_base = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/surge.conf"

[[rename_node]]
rename="!!GROUPID=0!!(^.*)@TAG - $1"
rename="!!GROUPID=1!!(^.*)@库洛米 - $1"
rename="!!GROUPID=2!!(^.*)@Orange - $1"
rename="!!GROUPID=3!!(^.*)@奶昔 - $1"


[[rename_node]]
match="!!GROUPID=0!!"
replace="TAG - $1"



managed_config_prefix = "http://home.man-her.tech:55500"

[[rulesets]]
import = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/base/rulesets.toml"

[[custom_groups]]
import = "https://github.com/HYBB-rash/MyProxyRepo/blob/main/base/groups.toml"