version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true

[[rulesets]]
import = "https://raw.githubusercontent.com/HYBB-rash/MyProxyRepo/main/base/rulesets.toml"

[[custom_groups]]
import = "https://github.com/HYBB-rash/MyProxyRepo/blob/main/base/groups.toml"

